### ISSUE TITLE
Frontend design updates

### ISSUE THREAD

**Issue by cimasm** [Sweng-Group-22/SWENG-22-Cisco#17]
The cancel button in the Modal.js popup needs a css file.
In BrowseLetter.css, we need to find a way to make different phrases sorted in multiple rows and columns when there is a big number of phrases present.

**Comment by AAjayiB** [comment]
For the cancel button i was thinking of using the same css as the submit button or maybe just using the whole submit button component but i'm not entirely sure how it works or if it'll be easy that way.
